version: '3'

services:
  node:
    container_name: node
    build: .
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: /bin/sh
