version: '3'

services:
  node:
    container_name: node
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: /bin/sh
